permalink: /:categories/:title/
encoding: "utf-8"
title: blog.xoppa.com
avatar: /assets/img/favicon/favicon-96x96.png

icons:
  rss: true
  email:
  github: xoppa
  bitbucket:
  twitter: xoppa
  facebook:
  google_plus:
  tumblr:
  behance:
  dribbble:
  flickr:
  instagram:
  linkedin:  # full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # full URL
  steam:
  wordpress:
  youtube:

google_analytics: UA-28042435-1
disqus: blogxoppacom
 
str_next: Next
str_prev: Prev
str_read_more: Read more...
str_search: Search
str_recent_posts: Recent posts
str_show_all_posts: Show all posts

recent_posts_num: 10

paginate: 50
paginate_path: page/:num

share_buttons: true
ogp:
  image_url: http://xoppa.github.io/assets/img/favicon/favicon-96x96.png
  fb:
    admin: # facebook admin id
    app_id: # facebook application id

markdown: redcarpet
redcarpet:
  extensions: ["autolink", "fenced_code_blocks", "strikethrough", "superscript", "with_toc_data", "tables", "footnotes", "no_intra_emphasis"]
highlighter: pygments

excerpt_separator: <more />

sass:
  sass_dir: _sass
  style: :compressed # or :expanded
 
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - vendor
